# Dependencies
markdown:         redcarpet
pygments:         false
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nerd in Action
tagline:          Code is poetry
url:              http://lixu.name
paginate:         5
baseurl:          /
author:
  name:           Xu Li
  url:            http://lixu.name
  email:          AthenaLightenedMyPath@gmail.com

# Custom vars
